name: flutter_project
description: A new Flutter application.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.3
  provider: ^5.0.0
  google_fonts: ^2.1.0
  cached_network_image: ^3.0.0
  rxdart: ^0.27.0
  shared_preferences: ^2.0.6
  logger: ^1.0.0
  geolocator: ^7.4.1
  geocoder: ^0.2.1
  flutter_icons: ^1.1.0
  flutter_map: ^0.14.0
  latlong2: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true